<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>Casko.Authentication.NemLogin3.Web.UI</PackageId>
    <Version>10.0.0</Version>
    <RootNamespace>Casko.DefaultsFor.NemLogin3.Web.UI</RootNamespace>
  </PropertyGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\Casko.Authentication.NemLogin3.Web\Casko.Authentication.NemLogin3.Web.csproj" />
  </ItemGroup>
</Project>
