<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="ITfoxtec.Identity.Saml2" Version="4.20.1" />
    <PackageVersion Include="ITfoxtec.Identity.Saml2.MvcCore" Version="4.20.1" />
    <PackageVersion Include="Yarp.ReverseProxy" Version="2.3.0" />
  </ItemGroup>
</Project>
